name: blueprint-compiler # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.8.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A markup language for GTK user interface files. # 79 char long summary
description: |
  GtkBuilder XML format is quite verbose, and many app developers don't like using WYSIWYG editors for creating UIs. Blueprint files are intended to be a concise, easy-to-read format that makes it easier to create and edit GTK UIs.
  Internally, it compiles to GtkBuilder XML as part of an app's build system. It adds no new features, just makes the features that exist more accessible.
  Another goal is to have excellent developer tooling--including a language server--so that less knowledge of the format is required. Hopefully this will increase adoption of cool advanced features like GtkExpression.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
parts:
  blueprint-compiler:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.gnome.org/jwestman/blueprint-compiler.git
    source-tag: 'v$SNAPCRAFT_PROJECT_VERSION'
    meson-parameters:
      - --prefix=/usr
    
apps:
  blueprint-compiler:
    command: usr/bin/blueprint-compiler
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
