name: blueprint-compiler
base: core24
adopt-info: blueprint-compiler
summary: A markup language for GTK user interface files.
website: https://jwestman.pages.gitlab.gnome.org/blueprint-compiler
source-code: https://gitlab.gnome.org/jwestman/blueprint-compiler
issues: https://github.com/jameswestman/blueprint-compiler-snap/issues
contact: https://matrix.to/#/#blueprint-language:matrix.org
description: |
  GtkBuilder XML format is quite verbose, and many app developers don't like using WYSIWYG editors for creating UIs. Blueprint files are intended to be a concise, easy-to-read format that makes it easier to create and edit GTK UIs.
  Internally, it compiles to GtkBuilder XML as part of an app's build system. It adds no new features, just makes the features that exist more accessible.
  Another goal is to have excellent developer tooling--including a language server--so that less knowledge of the format is required. Hopefully this will increase adoption of cool advanced features like GtkExpression.
license: GPL-2.0 or LGPL-2.1-or-later
grade: stable
confinement: classic
platforms:
  amd64:
  arm64:
  armhf:

parts:
  # launcher:
  #   plugin: dump
  #   source: .
  #   override-build: |
  #     cp launcher $CRAFT_PART_INSTALL/

  # ninja:
  #   plugin: nil
  #   source: https://github.com/ninja-build/ninja.git
  #   source-tag: "v1.12.0"
  #   source-depth: 1
  #   override-build: |
  #     rm -rf build
  #     rm -f ninja
  #     rm -f ninja_bootstrap
  #     sed -i 's_^#!/usr/bin/env python$_#!/usr/bin/env python3_g' configure.py
  #     ./configure.py --bootstrap
  #     mv ninja ninja_bootstrap
  #     rm -rf build
  #     ./ninja_bootstrap
  #     rm -f ninja_bootstrap
  #     mkdir -p $CRAFT_PART_INSTALL/usr/bin
  #     mv ninja $CRAFT_PART_INSTALL/usr/bin/
  #   build-packages:
  #     - python3
  #   override-prime: ""

  # meson-deps:
  #   after: [ninja]
  #   plugin: python
  #   source: https://github.com/mesonbuild/meson.git
  #   source-tag: "1.4.0"
  #   source-depth: 1
  #   build-packages:
  #     - python3-pip
  #   override-prime: ""

  blueprint-compiler:
    plugin: meson
    source: https://gitlab.gnome.org/jwestman/blueprint-compiler.git
    source-tag: 'v0.16.0'
    source-depth: 1
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --abbrev=0 --tags | cut -c 2-)
    meson-parameters:
      - --prefix=/snap/blueprint-compiler/current/usr
    organize:
      snap/blueprint-compiler/current: .
    build-packages:
      - meson
    prime:
      - -snap/blueprint-compiler

apps:
  blueprint-compiler:
    command: usr/bin/blueprint-compiler
    environment:
      GI_TYPELIB_PATH: /snap/gnome-46-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:/snap/gnome-46-2404-sdk/current/usr/lib/girepository-1.0:/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:/usr/lib/girepository-1.0:$GI_TYPELIB_PATH
      LD_LIBRARY_PATH: /snap/gnome-46-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/gnome-46-2404-sdk/current/usr/lib:/usr/lib/$CRAFT_ARCH_TRIPLET:/usr/lib:$LD_LIBRARY_PATH
